### PR TITLE
Pass the executing assembly to Harmony.PatchAll

### PR DESCRIPTION
**Pull request by fauxnik**
This fixes the issue of methods not being patched using the code provided by the template.

### CODE REVIEW

**Comment by Insprill** [comment]
If you don't pass in an assembly it implicitly uses the calling assembly ([source](https://github.com/pardeike/Harmony/blob/master/Harmony/Public/Harmony.cs#L74-L79)). I've used it like this in all of my mods ([Mapify](https://github.com/Insprill/dv-mapify/blob/master/Mapify/Mapify.cs#L53-L54), [Gauge](https://github.com/Insprill/dv-gauge/blob/master/Gauge/Gauge.cs#L25-L26)), and it works fine. Is there a reproducible problem when doing it this way?

**Comment by fauxnik** [comment]
That's strange. I was working on VR Zoom last night and had based the project updates off of this template. It took me a while to figure out why my patch wasn't getting called, but I eventually tracked it down to not having that call to `Assembly.GetExecutingAssembly()`. Adding it to [Main.cs](https://github.com/fauxnik/dv-vr-zoom/blob/main/VRZoom/Main.cs#L28) is what made the patch in [BindInputVr.cs](https://github.com/fauxnik/dv-vr-zoom/blob/main/VRZoom/BindInputVr.cs#L5) finally start working.

**Comment by Insprill** [comment]
That's interesting. Could you see if that's still the case, and if it is, try printing out what assembly their method is returning?

**Comment by fauxnik** [comment]
I'm not gonna have a chance to look into it anytime this weekend. Perhaps you could try building the VR Zoom mod without the `GetExecutingAssembly` call, and see if you have any luck with it? It wouldn't be the first time something that works for other folks doesn't work on my system.

**Comment by fauxnik** [comment]
So I just checked my mod again, and it does appear to work without passing the assembly. That said, I just noticed [this remark](https://github.com/pardeike/Harmony/blob/master/Harmony/Public/Harmony.cs#L72) in the source you linked to, which mentions that the argument-less version can get the wrong assembly in some cases.

> This method can fail to use the correct assembly when being inlined. It calls StackTrace.GetFrame(1) which can point to the wrong method/assembly. If you are unsure or run into problems, use <code>PatchAll(Assembly.GetExecutingAssembly())</code> instead.

Perhaps it's therefore simply more reliable to get and pass the executing assembly?

**Comment by Insprill** [comment]
I'm unsure why it would've gotten inlined if it did, but that may be a lack of knowledge about the Roslyn compiler. It doesn't hurt anything to do it this way, so we might as well even if only for the 1%.

**Review by Insprill — APPROVED** [review]
LGTM

**Pull request merged**
